[colors]
[colors.primary]
background = "#070703"
foreground = "#bdbfad"

[colors.normal]
black   = "#070703"
red     = "#979490"
green   = "#cde651"
yellow  = "#d4e85e"
blue    = "#d5e86d"
magenta = "#b4b3b1"
cyan    = "#dae98b"
white   = "#D2D99C"

[colors.bright]
black   = "#909060"
red     = "#c4c2bf"
green   = "#e7f69d"
yellow  = "#ecf7ab"
blue    = "#eef7b9"
magenta = "#e1e1e0"
cyan    = "#89892e"
white   = "#bdbfad"

[colors.cursor]
text   = "#070703"
cursor = "#bdbfad"
