# Background and foreground colors
background = #070703
foreground = #bdbfad

# Standard colors
palette = 0=#070703
palette = 1=#979490
palette = 2=#cde651
palette = 3=#d4e85e
palette = 4=#d5e86d
palette = 5=#b4b3b1
palette = 6=#dae98b
palette = 7=#D2D99C

# Bright colors
palette = 8=#909060
palette = 9=#c4c2bf
palette = 10=#e7f69d
palette = 11=#ecf7ab
palette = 12=#eef7b9
palette = 13=#e1e1e0
palette = 14=#89892e
palette = 15=#bdbfad
