$color = rgba(7, 7, 3, 1)
$inner_color = rgba(7, 7, 3, 0.66)
$outer_color = rgba(180, 179, 177, 1)
$font_color = rgba(189, 191, 173, 1)
$placeholder_color = rgba(189, 191, 173, 0.7)
$check_color = rgba(218, 233, 139, 1)
