background            #070703
foreground            #bdbfad

# black
color0  #070703
color8  #909060

# red
color1  #979490
color9  #c4c2bf

# green
color2  #cde651
color10 #e7f69d

# yellow
color3  #d4e85e
color11 #ecf7ab

# blue
color4  #d5e86d
color12 #eef7b9

# magenta
color5  #b4b3b1
color13 #e1e1e0

#cyan
color6  #dae98b
color14 #89892e

#white
color7  #D2D99C
color15 #bdbfad


